name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: install TDengine
        run: |
          cd TDengine
          mkdir debug
          cd debug
          cmake .. -DBUILD_HTTP=false -DBUILD_JDBC=false -DBUILD_TOOLS=false -DBUILD_TEST=off
          make -j 32
          sudo make install

      - name: start taosd
        run: nohup sudo sh taosd &

      - name: start taosadapter
        run: nohup sudo sh taosadapter &

      - name: test
        run:
          go mod tidy && go test -v ./...

      - name: Build
        run: |
          go mod tidy
          go build
